Repository EdricChan03/action-build-deploy-ghpages, pull requests merged in 2020-02, with the labels that each got.

#12 Added flag for skipping deployment
  README.md
  action.yml
  entrypoint.sh
Labels: priority: low, status: needs review, target: v2, type: enhancement

#10 Remove commented code, specify "commit" or "build" on pre/post commands.
  entrypoint.sh
Labels: priority: low, status: needs review, target: v2, type: enhancement

#9 Allow passing options to the `jekyll build` command.
  README.md
  action.yml
  entrypoint.sh
Labels: priority: low, status: accepted, target: v2, type: enhancement

#11 Add flag for showing full bundle install log output
  README.md
  action.yml
  entrypoint.sh
Labels: priority: low, status: needs rebase, target: v2, type: enhancement
